# Generated by Django 3.0 on 2019-12-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0)),
                ('contract_value', models.IntegerField(default=0)),
                ('contract_status', models.CharField(choices=[(1, 'Рассматривается'), (2, 'Принят'), (3, 'Отклонен'), (4, 'Изменен'), (5, 'Расторгнут')], max_length=20, unique=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_player', to=settings.AUTH_USER_MODEL)),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_team_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
