# Generated by Django 3.0 on 2019-12-14 13:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winners',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
