# Generated by Django 3.0 on 2019-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_tournament_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='preview_image',
            field=models.ImageField(default=None, upload_to='tournament_previews/'),
            preserve_default=False,
        ),
    ]
