# Generated by Django 3.0 on 2019-12-14 20:38

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_tournament_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('members', jsonfield.fields.JSONField(default=dict)),
                ('logo', models.ImageField(upload_to='static/team_logo/')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='preview_image',
            field=models.ImageField(upload_to='static/tournament_previews/'),
        ),
    ]
