# Generated by Django 3.0 on 2019-12-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20191214_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='start_day',
            new_name='start_date',
        ),
    ]
