# Generated by Django 3.0 on 2019-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20191214_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='01-01-1993'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='01-01-1993'),
        ),
    ]
